apiVErsion: apps/v1
kind: Service
metadata:
  name: service-2048
  namespace: game-2048
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector: #this will create service to deployment with the matching labels
    app.kubernetes.io/name: app-2048